services:
  redis:
    image: redis:8-alpine
    container_name: crdbl-redis
    command: redis-server --appendonly yes # AOF persistence
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'

  ipfs:
    image: ipfs/kubo:latest
    container_name: crdbl-ipfs
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./data/ipfs:/data/ipfs
    ports:
      - '5001:5001' # API
      - '8080:8080' # Gateway
      - '4001:4001' # Swarm (tcp)
      - '4001:4001/udp'
