services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes # AOF persistence
    volumes:
      - ./data/redis:/data
    # - redisdata:/data
    ports: ['6379:6379']
  # volumes:
  #   redisdata: {} # named volume lives outside the container
