services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes # AOF persistence
    volumes:
      - ./data/redis:/data
    # - redisdata:/data
    ports: ['6379:6379']
  # volumes:
  #   redisdata: {} # named volume lives outside the container

  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./data/ipfs:/data/ipfs
    ports:
      - '5001:5001' # API
      - '8080:8080' # Gateway
      - '4001:4001' # Swarm (tcp)
      - '4001:4001/udp'
