services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes # AOF persistence
    volumes:
      - ./data/redis:/data
    ports: ['6379:6379']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3

  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./data/ipfs:/data/ipfs
    ports:
      - '5001:5001' # API
      - '8080:8080' # Gateway
      - '4001:4001' # Swarm (tcp)
      - '4001:4001/udp'
    healthcheck:
      test: ['CMD', 'ipfs', 'id']
      interval: 10s
      timeout: 10s
      retries: 5
